#Define the goal
string hand #specify the hand in which the object will be held
---
#Define the result
uint32 total_views #number of views learned
---
#Define a feedback message
float32 percentage_completed
