/* Auto-generated by genmsg_cpp for file /home/irene/repos/ros_ws/sandbox/TFG/msg/EventHandler.msg */
#ifndef TFG_MESSAGE_EVENTHANDLER_H
#define TFG_MESSAGE_EVENTHANDLER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace TFG
{
template <class ContainerAllocator>
struct EventHandler_ {
  typedef EventHandler_<ContainerAllocator> Type;

  EventHandler_()
  : header()
  , hand()
  , event()
  , last_event()
  {
  }

  EventHandler_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , hand(_alloc)
  , event(_alloc)
  , last_event(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _hand_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  hand;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _event_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  event;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _last_event_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  last_event;


  typedef boost::shared_ptr< ::TFG::EventHandler_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::TFG::EventHandler_<ContainerAllocator>  const> ConstPtr;
}; // struct EventHandler
typedef  ::TFG::EventHandler_<std::allocator<void> > EventHandler;

typedef boost::shared_ptr< ::TFG::EventHandler> EventHandlerPtr;
typedef boost::shared_ptr< ::TFG::EventHandler const> EventHandlerConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::TFG::EventHandler_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::TFG::EventHandler_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace TFG

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::TFG::EventHandler_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::TFG::EventHandler_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::TFG::EventHandler_<ContainerAllocator> > {
  static const char* value() 
  {
    return "fa3dfe829c08e3650e3e356e080b85ec";
  }

  static const char* value(const  ::TFG::EventHandler_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xfa3dfe829c08e365ULL;
  static const uint64_t static_value2 = 0x0e3e356e080b85ecULL;
};

template<class ContainerAllocator>
struct DataType< ::TFG::EventHandler_<ContainerAllocator> > {
  static const char* value() 
  {
    return "TFG/EventHandler";
  }

  static const char* value(const  ::TFG::EventHandler_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::TFG::EventHandler_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
string hand\n\
string event\n\
string last_event\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::TFG::EventHandler_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::TFG::EventHandler_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::TFG::EventHandler_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::TFG::EventHandler_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.hand);
    stream.next(m.event);
    stream.next(m.last_event);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct EventHandler_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::TFG::EventHandler_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::TFG::EventHandler_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "hand: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.hand);
    s << indent << "event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.event);
    s << indent << "last_event: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.last_event);
  }
};


} // namespace message_operations
} // namespace ros

#endif // TFG_MESSAGE_EVENTHANDLER_H

